/**
 * @license
 * SPDX-License-Identifier: Apache-2.0
 */

import React, { useState, useEffect } from 'react';
import { 
  Equipment, 
  SubsystemType, 
  WorkOrder, 
  WorkOrderStatus, 
  AlertNotification, 
  MiningFleetKPIs 
} from './types';
import { 
  INITIAL_EQUIPMENT_LIST, 
  INITIAL_ALERTS, 
  INITIAL_WORK_ORDERS, 
  INITIAL_SPARE_PARTS, 
  INITIAL_FLEET_KPIS 
} from './data/miningData';
import { Header, ActiveTab } from './components/Header';
import { FleetManagementView } from './components/FleetManagementView';
import { DigitalTwinCoreView } from './components/DigitalTwinCoreView';
import { TelemetryStreamView } from './components/TelemetryStreamView';
import { CMMSMaintenanceView } from './components/CMMSMaintenanceView';
import { AlertsCenterView } from './components/AlertsCenterView';
import { ExecutiveAnalyticsView } from './components/ExecutiveAnalyticsView';
import { ReportsGeneratorView } from './components/ReportsGeneratorView';
import { TechnicalSpecsView } from './components/TechnicalSpecsView';
import { AIAssistantModal } from './components/AIAssistantModal';
import { api } from './api';

export default function App() {
  // Navigation State
  const [activeTab, setActiveTab] = useState<ActiveTab>('FLEET_MANAGEMENT');
  const [equipmentList, setEquipmentList] = useState<Equipment[]>(INITIAL_EQUIPMENT_LIST);
  const [selectedEquipment, setSelectedEquipment] = useState<Equipment>(INITIAL_EQUIPMENT_LIST[0]);
  const [selectedSubsystem, setSelectedSubsystem] = useState<SubsystemType>('SISTEMA_HIDRAULICO');
  
  // CMMS & Alerts State
  const [workOrders, setWorkOrders] = useState<WorkOrder[]>(INITIAL_WORK_ORDERS);
  const [alerts, setAlerts] = useState<AlertNotification[]>(INITIAL_ALERTS);
  const [kpis, setKpis] = useState<MiningFleetKPIs>(INITIAL_FLEET_KPIS);
  const [spareParts, setSpareParts] = useState(INITIAL_SPARE_PARTS);
  const [apiError, setApiError] = useState<string | null>(null);
  
  // Streaming & AI State
  const [isLiveStreaming, setIsLiveStreaming] = useState<boolean>(true);
  const [isAiCopilotOpen, setIsAiCopilotOpen] = useState<boolean>(false);

  // Initial data load from FastAPI/PostgreSQL
  useEffect(() => {
    const loadInitialData = async () => {
      try {
        const [fleet, alertsData, workOrdersData, sparePartsData, kpisData] = await Promise.all([
          api.getFleet(),
          api.getAlerts(),
          api.getWorkOrders(),
          api.getSpareParts(),
          api.getKpis(),
        ]);
        if (fleet.length > 0) {
          setEquipmentList(fleet);
          setSelectedEquipment((current) => fleet.find((eq) => eq.id === current.id) || fleet[0]);
        }
        setAlerts(alertsData);
        setWorkOrders(workOrdersData);
        setSpareParts(sparePartsData);
        setKpis(kpisData);
        setApiError(null);
      } catch (error) {
        console.error('FastAPI initial load failed:', error);
        setApiError('FastAPI/PostgreSQL no disponible. Se muestran datos locales de respaldo.');
      }
    };

    loadInitialData();
  }, []);

  // Live telemetry is generated by FastAPI and persisted in PostgreSQL.
  useEffect(() => {
    if (!isLiveStreaming) return;
    const interval = setInterval(async () => {
      try {
        const fleet = await api.simulateTelemetry();
        setEquipmentList(fleet);
        setApiError(null);
      } catch (error) {
        console.error('Telemetry stream failed:', error);
        setApiError('Se perdió conexión con la telemetría del backend.');
      }
    }, 3000);

    return () => clearInterval(interval);
  }, [isLiveStreaming]);

  // Keep selectedEquipment synchronized with equipmentList
  useEffect(() => {
    const updated = equipmentList.find((eq) => eq.id === selectedEquipment.id);
    if (updated) {
      setSelectedEquipment(updated);
    }
  }, [equipmentList]);

  // Handlers
  const refreshKpis = async () => {
    const currentKpis = await api.getKpis();
    setKpis(currentKpis);
  };

  const handleAcknowledgeAlert = async (alertId: string, user: string, notes: string) => {
    try {
      const updated = await api.acknowledgeAlert(alertId, user, notes);
      setAlerts((prev) => prev.map((alert) => (alert.id === alertId ? updated : alert)));
      await refreshKpis();
      setApiError(null);
    } catch (error) {
      console.error('Acknowledge alert failed:', error);
      setApiError('No se pudo persistir el reconocimiento de la alerta.');
    }
  };

  const handleCreateWorkOrder = async (newOT: WorkOrder) => {
    try {
      const created = await api.createWorkOrder(newOT);
      setWorkOrders((prev) => [created, ...prev.filter((ot) => ot.id !== created.id)]);
      setSpareParts(await api.getSpareParts());
      await refreshKpis();
      setApiError(null);
    } catch (error) {
      console.error('Create work order failed:', error);
      setApiError('No se pudo guardar la orden de trabajo en PostgreSQL.');
    }
  };

  const handleUpdateWorkOrderStatus = async (otId: string, newStatus: WorkOrderStatus) => {
    try {
      const updated = await api.updateWorkOrderStatus(otId, newStatus);
      setWorkOrders((prev) => prev.map((ot) => (ot.id === otId ? updated : ot)));
      setSpareParts(await api.getSpareParts());
      await refreshKpis();
      setApiError(null);
    } catch (error) {
      console.error('Update work order failed:', error);
      setApiError('No se pudo actualizar el estado de la orden de trabajo.');
    }
  };

  const handleCreateOTFromTwin = (eq: Equipment, subsystem: SubsystemType, reason: string) => {
    const newOT: WorkOrder = {
      id: `ot-${Date.now()}`,
      code: `OT-2026-${Math.floor(1000 + Math.random() * 9000)}`,
      equipmentId: eq.id,
      equipmentCode: eq.code,
      subsystem: subsystem,
      type: 'PRESCRIPTIVO',
      status: 'PLANIFICADA',
      priority: 'CRITICA_URGENTE',
      title: `Intervención Prescriptiva: ${reason}`,
      description: `Generada automáticamente desde el Gemelo Digital tras detectar degradación acelerada y RUL crítico (${eq.rulHours}h).`,
      iso14224Mechanism: 'Cavitación / Micro-fatiga cíclica según ISO 14224',
      iso14224FailureMode: 'Degradación de Presión Hidráulica / Fuga Interna',
      createdAt: new Date().toISOString(),
      scheduledStartDate: new Date(Date.now() + 43200000).toISOString(),
      estimatedDurationHours: 6.0,
      assignedLeadTech: 'Ing. Rodrigo Alarcón (Esp. Confiabilidad)',
      techniciansTeam: ['Téc. Fernando Ruiz', 'Téc. Javier Ccama'],
      requiredParts: [
        {
          partId: 'part-01',
          partNumber: 'CAT-384-9120',
          description: 'Bomba Principal de Pistones Axiales Rexroth A4VSO',
          quantity: 1,
          unitCostUsd: 14500
        }
      ],
      totalEstimatedCostUsd: 14500,
      triggerSource: 'ALERTA_GEMELO_DIGITAL',
      prescriptiveRecommendations: [
        'Aislar energía mediante bloqueo LOTO en bahía de mantenimiento.',
        'Inspeccionar válvula de alivio principal y sustituir conjunto de pistones axiales.',
        'Realizar rampa de prueba hidráulica y muestreo de aceite para conteo de partículas ISO 4406.'
      ],
      safetyChecklist: [
        { task: 'Bloqueo y Aislamiento de Energía Cero (LOTO)', completed: false },
        { task: 'Traba de seguridad en tolva y caballetes estructurales', completed: false },
        { task: 'Bandeja de contención para fluidos hidráulicos', completed: false }
      ]
    };

    void handleCreateWorkOrder(newOT);
    setActiveTab('CMMS_MAINTENANCE');
  };

  const handleCreateOTFromAlert = (alert: AlertNotification) => {
    const targetEq = equipmentList.find((eq) => eq.id === alert.equipmentId) || selectedEquipment;
    handleCreateOTFromTwin(targetEq, alert.subsystem, alert.title);
  };

  return (
    <div id="mining-digital-twin-app" className="min-h-screen bg-[#0F172A] text-slate-300 flex flex-col font-sans selection:bg-blue-500 selection:text-white">
      {/* Top Header & Navigation */}
      <Header
        activeTab={activeTab}
        onSelectTab={setActiveTab}
        kpis={kpis}
        onOpenAiCopilot={() => setIsAiCopilotOpen(true)}
        isLiveStreaming={isLiveStreaming}
        onToggleStreaming={() => setIsLiveStreaming(!isLiveStreaming)}
      />

      {apiError && (
        <div className="bg-amber-950/60 border-b border-amber-700/60 px-4 py-2 text-center text-xs font-mono text-amber-200">
          {apiError}
        </div>
      )}

      {/* Main Container Body */}
      <main className="flex-1 max-w-7xl w-full mx-auto p-4 sm:p-6">
        {activeTab === 'FLEET_MANAGEMENT' && (
          <FleetManagementView
            equipmentList={equipmentList}
            selectedEquipment={selectedEquipment}
            onSelectEquipment={setSelectedEquipment}
            onNavigateToDigitalTwin={(eq) => {
              setSelectedEquipment(eq);
              setActiveTab('DIGITAL_TWIN_CORE');
            }}
          />
        )}

        {activeTab === 'DIGITAL_TWIN_CORE' && (
          <DigitalTwinCoreView
            equipment={selectedEquipment}
            equipmentList={equipmentList}
            onSelectEquipment={setSelectedEquipment}
            selectedSubsystem={selectedSubsystem}
            onSelectSubsystem={setSelectedSubsystem}
            onCreateWorkOrderFromTwin={handleCreateOTFromTwin}
            onOpenAiDiagnostic={() => setIsAiCopilotOpen(true)}
          />
        )}

        {activeTab === 'TELEMETRY_STREAM' && (
          <TelemetryStreamView
            equipment={selectedEquipment}
            equipmentList={equipmentList}
            onSelectEquipment={setSelectedEquipment}
            isStreaming={isLiveStreaming}
            onToggleStreaming={() => setIsLiveStreaming(!isLiveStreaming)}
          />
        )}

        {activeTab === 'CMMS_MAINTENANCE' && (
          <CMMSMaintenanceView
            workOrders={workOrders}
            spareParts={spareParts}
            equipmentList={equipmentList}
            onCreateWorkOrder={handleCreateWorkOrder}
            onUpdateWorkOrderStatus={handleUpdateWorkOrderStatus}
          />
        )}

        {activeTab === 'ALERTS_CENTER' && (
          <AlertsCenterView
            alerts={alerts}
            onAcknowledgeAlert={handleAcknowledgeAlert}
            onCreateOTFromAlert={handleCreateOTFromAlert}
          />
        )}

        {activeTab === 'EXECUTIVE_ANALYTICS' && (
          <ExecutiveAnalyticsView
            kpis={kpis}
            equipmentList={equipmentList}
          />
        )}

        {activeTab === 'REPORTS_GENERATOR' && (
          <ReportsGeneratorView
            equipmentList={equipmentList}
            kpis={kpis}
            workOrders={workOrders}
          />
        )}

        {activeTab === 'TECHNICAL_SPECS' && (
          <TechnicalSpecsView />
        )}
      </main>

      {/* AI Copilot Interactive Modal */}
      <AIAssistantModal
        isOpen={isAiCopilotOpen}
        onClose={() => setIsAiCopilotOpen(false)}
        currentEquipment={selectedEquipment}
        equipmentList={equipmentList}
      />

      {/* Technical Status Footer */}
      <footer className="h-8 bg-[#0F172A] border-t border-slate-800 px-4 sm:px-6 flex items-center justify-between text-[10px] font-mono text-slate-500">
        <div className="truncate">ISO 14224 COMPLIANT | ENCRYPTION: AES-256 | NODE: LATAM-ANDES-04</div>
        <div className="flex gap-4 shrink-0">
          <span className="hidden sm:inline">MTBF: <span className="text-white font-bold">{kpis.meanTimeBetweenFailuresHours}h</span></span>
          <span className="hidden sm:inline">MTTR: <span className="text-white font-bold">{kpis.meanTimeToRepairHours}h</span></span>
          <span>AVAILABILITY: <span className="text-emerald-400 font-bold">{kpis.physicalAvailabilityPct}%</span></span>
        </div>
      </footer>
    </div>
  );
}

